module.exports = [
    {
        country: 'France',
        city: 'Paris',
        housesit: true,
        petsit: false,
        title: 'Paris Two Bedroom',
        date: '03/18/24 - 03/25/24',
   },
   {
        country: 'Ireland',
        city: 'Kinsale',
        housesit: true,
        petsit: true,
        title: 'Two Dogs and Two Cats and Lots of Plants',
        date: '06/05/24 - 06/26/24',
        img: '/seedimages/dog1.jpg',
        img: '/seedimages/dog2.jpg',
        img: '/seedimages/cat4.jpg',
        img: '/seedimages/cat6.jpg',
   },
   {
        country: 'Germany',
        city: 'Munich',
        housesit: true,
        petsit: true,
        title: 'Munich One Dog, only speaks German',
        date: '01/12/24 - 01/20/24',
        img: '/seedimages/dog4.jpg',
   },
   {
        country: 'United States',
        city: 'New York',
        housesit: true,
        petsit: true,
        title: 'GREAT VIEW of Central Park, 1 Dog',
        date: '02/12/24 - 02/25/24',
        img: '/seedimages/dog3.jpg',
   },
   {
        country: 'United States',
        city: 'San Francisco',
        housesit: true,
        petsit: false,
        title: 'Ocean View, 4 Bedroom',
        date: '07/10/24 - 07/17/24',
   },
   {
        country: 'Japan',
        city: 'Osaka',
        housesit: true,
        petsit: false,
        title: '1 Month Stay, 2 Bedroom',
        date: '04/02/24 - 04/30/24',
   },
   {
        country: 'Germany',
        city: 'Berlin',
        housesit: true,
        petsit: true,
        title: 'Three Cats, in heart of Berlin',
        date: '08/10/24 - 08/21/24',
        img: '/seedimages/cat3.jpg',
        img: '/seedimages/cat8.jpg',
        img: '/seedimages/cat7.jpg',
   },
   {
        country: 'Canada',
        city: 'Montreal',
        housesit: true,
        petsit: true,
        title: 'One Friendly Snake and One Cat w/ an attitude',
        date: '02/22/24 - 02/28/24',
        img: '/seedimages/cat2.jpg',
        img: '/seedimages/snake.jpg',
   },
   {
        country: 'Italy',
        city: 'Florence',
        housesit: true,
        petsit: false,
        title: '5 Bedroom in wine country',
        date: '06/11/24 - 06/24/24',
   },
   {
        country: 'Portugal',
        city: 'Porto',
        housesit: true,
        petsit: true,
        title: 'Two cats, one dog, near beach',
        date: '07/18/24 - 07/26/24',
        img: '/seedimages/cat1.jpg',
        img: '/seedimages/cat5.jpg',
        img: '/seedimages/dog6.jpg',
   },
   {
        country: 'Spain',
        city: 'Seville',
        housesit: true,
        petsit: true,
        title: 'One dog, one bird',
        date: '05/08/24 - 05/16/24',
        img: '/seedimages/bird.jpg',
        img: '/seedimages/dog7.jpg',
   },
   {
        country: 'Norway',
        city: 'Oslo',
        housesit: true,
        petsit: true,
        title: 'Three Dogs',
        date: '09/01/24 - 09/10/24',
        img: '/seedimages/dog5.jpg',
        img: '/seedimages/dog9.jpg',
        img: '/seedimages/dog10.jpg',
   }
] // 12